### ISSUE TITLE
do you suggest using the block entity tick acceleration?

### ISSUE THREAD

**Issue by Legendmanj** [snackbag/TT20#7]
does the block enity tick acceleration make the enitiy to stop lagging as it was before, is there any way i can fix my Cant keep up, running ticks behing error? gg (;

**Comment by JXSnack** [comment]
Block entity tick acceleration is pretty buggy, because it may cause more performance issues - I'm planning on making a dynamic system so that block entities that aren't the main lag cause don't get accelerated, but innocent ones run on normal speed.

In short: I don't recommend it, as it may reduce TPS even more
